Gamepad:
    file: Gamepad_Normalize 
    varclass: Gamepad
    frequency: 1000000
ProfileA:
    file: Thruster_Profile
    varclass: FormulaApply
    frequency: 100
    activate: -1
    max_percentage: 100
    formula_modifier: 30
ProfileB:
    file: Thruster_Profile
    varclass: FormulaApply
    frequency: 100
    activate: 1
    max_percentage: 70
    formula_modifier: 30
ThrusterFL:
    file: Thruster_Message
    varclass: Thruster
    name: ThrusterFL
    address: 0x017
    invert: True
    frequency: 10
    gui: True
ThrusterFR:
    file: Thruster_Message
    varclass: Thruster
    name: ThrusterFR
    address: 0x015
    invert: True
    frequency: 10
    gui: True
ThrusterBL:
    file: Thruster_Message
    varclass: Thruster
    name: ThrusterBL
    address: 0x018
    invert: True
    frequency: 10
    gui: True
ThrusterBR:
    file: Thruster_Message
    varclass: Thruster
    name: ThrusterBR
    address: 0x01B
    invert: False
    frequency: 10
    gui: True
ThrusterUL:
    file: Thruster_Message
    varclass: Thruster
    name: ThrusterUL
    address: 0x016
    invert: True
    frequency: 10
    gui: True
ThrusterUR:
    file: Thruster_Message
    varclass: Thruster
    name: ThrusterUR
    address: 0x01A
    invert: True
    frequency: 10
    gui: True

