Gamepad:
    file: Gamepad_Normalize
    varclass: Gamepad
    frequency: 1000000
Formula:
    file: Thruster_Profile
    varclass: FormulaApply
    frequency: 100
ThrusterFL:
    file: Thruster_Message
    varclass: Thruster
    address: 0x015
    invert: False
    frequency: 10
ThrusterFR:
    file: Thruster_Message
    varclass: Thruster
    address: 0x016
    invert: False
    frequency: 10
ThrusterBL:
    file: Thruster_Message
    varclass: Thruster
    address: 0x017
    invert: False
    frequency: 10
ThrusterBR:
    file: Thruster_Message
    varclass: Thruster
    address: 0x018
    invert: False
    frequency: 10
ThrusterUL:
    file: Thruster_Message
    varclass: Thruster
    address: 0x019
    invert: False
    frequency: 10
ThrusterUR:
    file: Thruster_Message
    varclass: Thruster
    address: 0x01A
    invert: False
    frequency: 10

