Gamepad:
    file: Gamepad_Normalize 
    varclass: Gamepad
    frequency: 1000000
ProfileA:
    file: Thruster_Profile
    varclass: FormulaApply
    frequency: 100
    activate: 'A'
    max_percentage: 100
    formula_modifier: 30
ProfileB:
    file: Thruster_Profile
    varclass: FormulaApply
    frequency: 100
    activate: 'B'
    max_percentage: 70
    formula_modifier: 30
ProfileC:
    file: Thruster_Profile
    varclass: FormulaApply
    frequency: 100
    activate: 'C'
    max_percentage: 30
    formula_modifier: 30
ProfileD:
    file: Thruster_Profile
    varclass: FormulaApply
    frequency: 100
    activate: 'D'
    max_percentage: 100
    formula_modifier: 0.1    
ThrusterFL:
    file: Thruster_Message
    varclass: Thruster
    name: ThrusterFL
    address: 0x017
    invert: True
    frequency: 10
    gui: True
ThrusterFR:
    file: Thruster_Message
    varclass: Thruster
    name: ThrusterFR
    address: 0x015
    invert: True
    frequency: 10
    gui: True
ThrusterBL:
    file: Thruster_Message
    varclass: Thruster
    name: ThrusterBL
    address: 0x018
    invert: True
    frequency: 10
    gui: True
ThrusterBR:
    file: Thruster_Message
    varclass: Thruster
    name: ThrusterBR
    address: 0x01B
    invert: False
    frequency: 10
    gui: True
ThrusterUF:
    file: Thruster_Message
    varclass: Thruster
    name: ThrusterUF
    address: 0x016
    invert: True
    frequency: 10
    gui: True
ThrusterUB:
    file: Thruster_Message
    varclass: Thruster
    name: ThrusterUB
    address: 0x01A
    invert: True
    frequency: 10
    gui: True

